services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\SharedBundle\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Doctrine/'
      - '../src/SharedBundle.php'